/**
 * Hand-written wrapper. DO NOT regenerate this file.
 *
 * The model data lives in `vercel-gateway.models.json` (regenerated by
 * `fetch-vercel-gateway-models.ts`). This wrapper re-exports it typed so
 * consumers can keep `import { models } from './vercel-gateway.models'`.
 *
 * The data is loaded via `JSON.parse(readFileSync(...))` rather than an
 * `import ... with { type: 'json' }` attribute so the loader doesn't have
 * to support JSON import attributes.
 */

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export interface VercelGatewayCatalogModel {
  id: string
  object?: string
  created?: number
  owned_by?: string
  type?: string
  tags?: Array<string>
  modalities?: {
    input?: Array<string>
    output?: Array<string>
  }
  supported_parameters?: Array<string>
  [key: string]: unknown
}

const __dirname = dirname(fileURLToPath(import.meta.url))
const DATA_PATH = resolve(__dirname, 'vercel-gateway.models.json')

export const models: Array<VercelGatewayCatalogModel> = JSON.parse(
  readFileSync(DATA_PATH, 'utf-8'),
)
